### ISSUE TITLE
Plan for Release Scheduling and Releases

### ISSUE THREAD

**Issue by rye** [kotct/docket-old#12]
As we move forward and continue to iterate our version counter, I find it important to stress what the schedule for releases should be. While [this standard](http://semver.org/) does not really apply necessarily to our situation since our system is an end product and not an API (and therefore cannot be considered to be using said standard, citing rule 1 under the specification), we should definitely bear a similar tracking system in mind.

@cg505's comment on d25721326bf2c537feaaf5a3f92cd6ad6e8ecd82 raises a valid point, but I'd say that the time spent on a commit is not really that important. Really small changes can greatly affect a project (cite the whole Linux project, in which small ~7-line changes can fix a component's performance drastically), so what matters is really the importance of the changes.

In terms of our little project, though, I'd say small changes like that in 6ae1d2e7e22464f8c8a166580456069ebf3c4094 would not be worthy of iterating the version counter.

We should develop a plan for both naming version strings and also when we are to release.

**Comment by cg505** [comment]
I would propose the following interpretation of the system that is linked to:
- MAJOR version increment when there is a _substantial_ change in the backend or the frontend (or both) OR we have collected enough minor versions that the current version would be _extremely_ preferable over the last major version.
- MINOR version increment when there is a major feature implemented OR we have collected enough patch versions that the current version would be _substantially_ preferable over the last minor version.
- PATCH version increment when there is a minor feature implemented or a major bug fix OR we have collected enough minor bug fixes that the current version would be _clearly_ preferable over the last minor version.

In most cases, I was thinking that the number collected would be somewhere between five and ten.

As well I would like to propose that a patch release can happen with the signoff of two people, but a major or minor release would take all three of us signing off.

How do these proposals sound?

**Comment by rye** [comment]
I agree. I would say that the number collected, however, should not be limited. We could easily have >16 PATCHes and MINOR's, depending on how much change happens.

**Comment by Sammidysam** [comment]
I think that we should not release a new minor version only because of bug fixes.  Bug fixes should always be patches, and minor versions occur when new major features are implemented.

We really should not have to worry about major versions right now.  We can discuss it if the time arises where it would make sense.  In any case, 1.0.0 is when we feel that everything that our program will do is fully created and basically perfect.

I also agree with @four04 that we can have many patches and minor versions; much more than five to ten.

**Comment by Sammidysam** [comment]
Also, because we are using branches, we can do really awesome branch work for the next minor version and subsequent minor versions.  This requires that we have a branch where we do all of our work for the next minor version.

How I think that we should approach minor versions is that we should decide on one component of Docket that we are going to make much better for the next minor version.  That means adding features to it, making it pretty, and making it bug-free.  For 0.2.0 I suggest immensely improving the docket interface, because right now it is kind of ugly.  It is also the most important part of the program.  We should probably have it the best out of all of the other components first.

Once we decide what our focus for the next minor version is, we create a branch for work towards that improvement.  To make development easy on that branch, we will branch off of the feature branch to make changes, and then merge into the feature branch.  This is similar to in Smart Create, where we have `touch-clone` as the feature branch and we branch off of `touch-clone` sometimes to add things.  We should branch more with this program, though.  We can treat the feature branch as master in this case.

We can also do the small patch fixes on separate branches that are branched off of master, outside of the feature branch.  For example, if we needed a quick bug fix, we can make a branch off of master for it, and then merge to master when done.  Then, we merge master to our feature branch to ensure that it is up-to-date with bug fixes.  Finally, when we decide that our feature is complete, we merge the feature branch to master and create a new release.

Does this sound good?  If so, what do you want the focus for 0.2.0 to be?

**Comment by cg505** [comment]
It sounds good, but what is a patch version under your scheme?

**Comment by Sammidysam** [comment]
I believe the items below would be patches.
- Major bug fix
  
  An example of this is fixing the page crashing under certain conditions.  We would want to get that out to users _as soon as possible_.
- Minor bug fixes
  
  These would be, for example, the fix for Heroku compatibility, and other small fixes.
- Small features outside of the focus features
  
  For example, if we were working on the docket as our focus feature for 0.2.0 and we wanted to add buttons in places outside of the docket, it would be small features outside of the focus features and would go in a patch.  It could also go in the minor version, depending on how urgent we feel the need to have users be able to use the small feature is.
- Preview of next minor version
  
  This seems weird, but it can actually work at times.  For example, in Smart Create we released version 0.0.1 as "Touch Clone without Arguments".  Therefore, it was making progress towards it being a clone of the touch command, but it was not quite there yet.

**Comment by cg505** [comment]
It sounds good to me.

**Comment by Sammidysam** [comment]
So what do we want the focus for 0.2.0 to be?

**Comment by cg505** [comment]
I thought the docket interface sounded fine.

**Comment by rye** [comment]
I'd recommend that we create a milestone for each upcoming release as it becomes the next one, and then create issues for each thing that we want to do as part of that release. Either that, or we create a "Next Release" milestone, where we place stuff and then move it once we're done. I'll create a milestone now.

In terms of 0.2.0, I'd say some bug fixes and continuity fixes would be good, as well as that docket interface.

**Comment by cg505** [comment]
I think we should create new milestones for each release.

**Comment by rye** [comment]
Yeah.

EDIT: Each major/minor/patch or just each minor/major or just each major?

**Comment by Sammidysam** [comment]
I think each minor and major.  I agree that milestones are good.  The milestone that we made is good as well.  We should not make a 1.0.0 milestone until a while in the future when we feel that our program is almost at 1.0.0 and our next release should be 1.0.0.  So it looks like the focus for 0.2.0 is
- improve the docket interface.
- improve the overall design.

That is very much doable.  Do you want to make a branch called `visual-improvements` to be our feature branch and then make two branches off of that, one for general design and one for docket design?

**Comment by cg505** [comment]
Why don't we just name the feature branch v0.1.1?

**Comment by cg505** [comment]
I mean v0.2.0.

**Comment by Sammidysam** [comment]
That works too.

**Comment by rye** [comment]
I'd say two branches are in order: `docket-interface` and `design-improvements`.

EDIT: These could be branched from a more central branch called `visual-improvements`.

**Comment by Sammidysam** [comment]
Yep, and they will both be branched off of the branch v0.2.0 which is branched off of master.

**Comment by rye** [comment]
I'll go ahead and create them now.

**Comment by Sammidysam** [comment]
Also, I think that we should keep bug fixes out of 0.2.0 if we can.  Generally patches are better for that.

**Comment by Sammidysam** [comment]
We can also delete the following branches.
- backend
- visual-tweaks
- word-fixes

**Comment by Sammidysam** [comment]
And also make a bug-fix branch.

**Comment by cg505** [comment]
So whenever we want to make a patch version, we merge to master, tag HEAD, then switch to the feature branch and merge in master?

**Comment by Sammidysam** [comment]
Yep.

**Comment by Sammidysam** [comment]
Are the branch deletions that I am going to make okay?

**Comment by rye** [comment]
Yes.

**Comment by Sammidysam** [comment]
Okay, deletions done.

**Comment by cg505** [comment]
For small fixes that are only one commit and alone would not make up a patch version, should I make a branch off master called fixes that can be merged into master and released every once in a while when they accumulate?

**Comment by Sammidysam** [comment]
I made an earlier comment that said "And also make a bug-fix branch."  That did not get done, but yeah, I think that we can make a branch called `fixes` used for those.  That will work.  We can pull it up to date whenever we need to make a new fix.

**Comment by rye** [comment]
Yeah, the `fixes` branch sounds like a good idea.

**Comment by Sammidysam** [comment]
I have created the branch.

**Comment by cg505** [comment]
It appears to be branched off of `docket-interface`, whereas I believe it's parent should be `master`. Force pushing to correct, but please tell me if I'm wrong.

**Comment by Sammidysam** [comment]
That is me forgetting which branch I created it from.  You are right.

**Comment by Sammidysam** [comment]
Should we close now that we know what designates what kind of release?

**Comment by cg505** [comment]
Yes.
