### ISSUE TITLE
Plan for Features and Such

### ISSUE THREAD

**Issue by rye** [kotct/docket-old#3]
So, I'm interested in what we want to do exactly with this, so I'm just starting a To-do-like list.
- [x] Users can subscribe to classes
- [x] Users can post information about assignments in each of their classes
- [x] Users can post information about tests in each of their classes
- [x] Users can see information about assignments in all of their classes collectively
- [x] Users can see information about tests in all of their classes collectively

Anything else? Perhaps we should have some duplicate detection for deciding if something is similar enough to another test or assignment that it may be a duplicate? That's the only problem with this kind of an open system.

**Comment by Sammidysam** [comment]
Is this the list of features that we should at least have doable for the release of 0.1.0?  Should we focus all of our attention on finishing the necessary steps towards 0.1.0 (I am assuming those would be these)?  As in, should I work on these before switching to using Rails Bootstrap Navbar for the navbar, switching the docket interface to look more like the physical docket, and adding Wikiquote support?

**Comment by rye** [comment]
Whatever divisions must be done to get these implemented, they can go into whichever versions are necessary. I'd imagine 0.1.0 would probably have the basic functionality that we're looking to provide.

**Comment by Sammidysam** [comment]
I agree.  I think that we should view 0.1.0 as allowing users to do everything that they will be able to do in 1.0.0, but not completely bug-free or fully functional.  However, it must be usable.  Therefore, all of the items above must be at least somewhat done by the time that 0.1.0 rolls around.  They do not need to be perfect by any means.

I am going to finish switching to Rails Bootstrap Navbar because I'd like to make some changes to the navbar and it is way easier with that gem.  I am going to save Wikiquote and changing the docket interface for after 0.1.0, because they are improvements that are not really necessary.  Adding a duplicate detector system should be saved for after 0.1.0 as well.

**Comment by cg505** [comment]
Two things.

First: Do we really need to have the app look like the actual docket? It seems a like our own design 1) would look better and 2) could be more functional.

Second: Do you think we should switch to cancan? There is some very simple auth stuff that I have built in, but cancan is very powerful and would be incredibly useful should we want to limit people to adding assignments and exams to classes they are in.

**Comment by Sammidysam** [comment]
We can worry about the look of the docket after 0.1.0 is finished.  I really just mean that the interface now is probably not the best for the future (which is likely because it is not finished yet).  I did not mean to make it look exactly like the school docket.  After 0.1.0 I'll think about the interface that I would like best more.

**Comment by rye** [comment]
I think it would be nice to have some kind of hints that the docket interface itself is displaying stuff similarly to a real-life docket, but that doesn't necessarily need to be the case. Stuff like spiral binding on the left side could be added, but it seems too cheesy to me. I'd think that some kind of weekly planner-style interface for displaying everything in a given week would be good, with support later on for alerts and prioritization of assignments.

**Comment by rye** [comment]
If @btgeek wants to put this on WLCSC and make it a "official WLCSC application," we may be able to add support for LDAP/AD groups and permissions through that or whatnot (Is this possible, @btgeek?). For now, though, CanCan sounds like a good idea. Stuff should, as it always should have and should continue to be, be standardized, though (don't make it ugly). More powerful auth-y stuff would be good.

**Comment by braddoeswebdev** [comment]
I don't see us officially adopting this one.  Since we're moving everybody to Google & the Calendar supports all this stuff already... why reinvent the wheel?

In any case, optional LDAP auth is fairly easy to add - add the LDAP gem, grab the 2 files out of lib, and look at how I actually auth people in the relevant controllers/models in any of my projects :smile: CanCan is a good thing too if your permissions are going to be even remotely non-trivial.

**Comment by rye** [comment]
Oh, well.

**Comment by Sammidysam** [comment]
People use Google Calendar for designating when assignments/work is due?  I never knew that.  I thought people typically used it for marking when events are.  I guess there is Google Tasks, but I have never personally used that.

I feel like Google Calendar does most of what we are trying to do here, yes, but they do it a lot worse than it will be when we make it.  Our program is more specific, whereas Google's is more broad.  Each person who decides to use Google Calendar for the same thing as what we are doing will have to spend a lot more time setting it up to work as they want it to.  Even if WLCSC doesn't adopt it, we should still host this program with Heroku or something anyway, because I will definitely want to use it.  When I came up with the idea, I never expected WLCSC to actually use it anyway.

**Comment by cg505** [comment]
This. Literally, my thoughts exactly.

**Comment by rye** [comment]
Yeah. It'd be nice to have hosting, but we don't really need that. If people (in general) don't want to use our system once it's done, it's their loss.

**Comment by cg505** [comment]
Heroku will be fine.

**Comment by Sammidysam** [comment]
Will we need to prevent users from joining as easily then, so that we don't have too much data?

**Comment by braddoeswebdev** [comment]
I kept all my assignments & stuff in Google Calendar when I was in school and it worked just fine - I just made an event when the thing was due.  I don't know of any teachers or students here that are doing it yet.  However, that's one of the things that we'll be highly recommending that teachers set up to be shared with their classes as we continue transitioning our lives to Google - we can more or less automatically create Google Groups from class rosters out of Harmony, so there's almost nothing to it.  

Heroku hosting would suffice for a while.  If it gets popular & free Heroku can't handle it anymore, you could start charging :wink: That or you could implement some sort of sharding system where each server has a certain set of users/classes on it, and then others can be added via API.  

As far as excess user prevention, just have a sign up password or an invitation system.

**Comment by rye** [comment]
Or just create a user and make the administrators add people.

And, if I have to, we could probably set up a server for this somewhere.

**Comment by cg505** [comment]
I was just thinking we would have a secret code system with an occasionally-changing secret code (possibly in a config db table) and then an aggressive ban policy.

**Comment by rye** [comment]
Or, perhaps a signup-y Google Drive form? I'll get started on one, even if we don't use it.

**Comment by Sammidysam** [comment]
A sign up form would probably work well.  I think that's a good idea.  Then we can have a group of users that can make new users that we can call administrators.

I think that this behavior should be optional, based on a boolean value in a JSON or YAML object somewhere.  Then, if we were granted lots of free space, we could simply set the setting to `false` and the website would work with anybody being able to register.

**Comment by rye** [comment]
In terms of auth, we need to make sure that everything makes sense. The more permissions, the better, as far as I am concerned.

For now, I'd think it'd be best if we only invited the people who sign up, and then perhaps publicize it more once everything's ironed out and pretty.

**Comment by Sammidysam** [comment]
I agree with the invitations.  Ideally 1.0.0 is the version number that we decide to publicize.

**Comment by Sammidysam** [comment]
By the way, are releases going on the `release` branch?  I thought that `master` would be a good place for that.

**Comment by rye** [comment]
Releases can go wherever. I would say the release branch could be merged to at each release, and that would be what we "tag" or "release" using GitHub.

**Comment by rye** [comment]
What matters is that we are consistent.

**Comment by Sammidysam** [comment]
Then after that they would get merged to master?

**Comment by rye** [comment]
No, we'd merge everything to master and then merge master to release.

**Comment by Sammidysam** [comment]
That makes having the release branch seem a bit pointless.  You're saying we would only create releases on the release branch?

**Comment by rye** [comment]
Basically. Alternatively we could just use master.

**Comment by Sammidysam** [comment]
I think just using master sounds better.

**Comment by cg505** [comment]
So merging to master does not in itself constitute a release, however, tags for releases should be done on master.

Is this right?

**Comment by rye** [comment]
Yes.

**Comment by Sammidysam** [comment]
I prefer only pushing to master during releases, though in looking at many important repositories, they all push to master when not releasing.  Therefore, our rule for pushing to master can be that the code must be stable (no known bugs).  Does that sound good?

**Comment by rye** [comment]
Yeah, that's a good rule to follow. If you can avoid pushing directly to master, do it. Use branches. It makes everything easier.

**Comment by Sammidysam** [comment]
That sounds good.  Branches can also be merged whenever the creator thinks that the code is stable, not only when a release is about to happen.

Hooray for establishing rules.

**Comment by Sammidysam** [comment]
Because we have established how our system will work, the branch `release` will be deleted.

**Comment by rye** [comment]
Okay.

**Comment by cg505** [comment]
Our goal is to release v0.1.0 tomorrow.

We need to be focusing mainly on stabilization and prettification.

I would like to set up Heroku hosting for developers to use as if it were in production. I can work on setting up for production. Communication regarding Heroku should be via email for security reasons. I would like to deploy to Heroku following the release.

**Comment by cg505** [comment]
I will not be available for basically all of today, so don't wait for any input from me on anything.

**Comment by cg505** [comment]
Are we ready for release?

**Comment by Sammidysam** [comment]
I think that it looks good enough for 0.1.0 to me.  We'll need to merge `backend` I believe.

**Comment by rye** [comment]
I think so.

**Comment by rye** [comment]
I'll go ahead and take care of the merges.

**Comment by Sammidysam** [comment]
Should we close now that we figured out our main features?

**Comment by rye** [comment]
I would say so.
