### ISSUE TITLE
Do we really need a course number?

### ISSUE THREAD

**Issue by cg505** [kotct/docket-old#59]
When I put the course number field in the database schema, it may have been because I couldn't think of anything else. Is it really something we need?

**Comment by rye** [comment]
Yes. I still use it quite a lot. You guys should get a database dump from Harmony of the relationships between the course name and the course numbers next year so that you can populate the database. Zach gave me it this year. I can email it to you if you want it. But it's helpful for me. We should just not require it when creating the course, and hide it from people.

**Comment by cg505** [comment]
Okay. That last sentence is a good idea.

**Comment by cg505** [comment]
So we need to leave the course number in the db, but hide it.

**Comment by rye** [comment]
Yeah. We could also add a "Mass assign course numbers" UI for admins so that they can fill in the course numbers for the courses that people are in. Or, we could do some magic on CSV files that we get from these DB dumps and do it automagically. But we should keep it in the DB. Since your question is answered, I'm closing.

**Comment by Sammidysam** [comment]
Why are they helpful, exactly?

**Comment by rye** [comment]
They're a shorthand that can be used to accurately represent all courses, regardless of their long name. In my actual paper docket, I've always used these coursebook numbers or something very similar.

**Comment by Sammidysam** [comment]
Ah, okay.  I guess they are good to keep, but good to be hidden from the users.

**Comment by rye** [comment]
Yep.
