### ISSUE TITLE
Docket/Welcome Controller Duplication

### ISSUE THREAD

**Issue by cg505** [kotct/docket-old#7]
It seems like the docket controller and the welcome controller are going to end up serving very similar purposes. Is it worth it to keep them separate, or should we just have one controller instead of these two separate ones?

**Comment by rye** [comment]
If we're going to use welcome as a sort of "dashboard" for the user, showing information about their upcoming assignments, tests, and events, we should rename it to "dashboard." Else, I would just recommend using docket and removing welcome.

**Comment by cg505** [comment]
@Sammidysam? What do you think?

**Comment by Sammidysam** [comment]
In response to @four04's comment, isn't the docket simply a dashboard?  I guess the docket focuses more on day-to-day instead of an overview though.

I am not sure what a welcome page would have instead of a docket in the first place.  I think we just want the docket to be the home page once the users are signed in, because it is what the program is based around.  It would seem weird having a welcome page that isn't the docket.  I assume the docket is what people come for in the first place.

**Comment by cg505** [comment]
Okay, so I'll be removing the welcome controller, and pointing root to `docket#index`.

**Comment by Sammidysam** [comment]
Sounds good.
